name: .NET CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Find solution file
      run: |
        SOLUTION_FILE=$(find . -name "*.slnx" | head -n 1)
        if [ -z "$SOLUTION_FILE" ]; then
          echo "❌ Файл .slnx не найден!"
          exit 1
        fi
        echo "SOLUTION_PATH=$SOLUTION_FILE" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release

    - name: Run tests
      run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --configuration Release --verbosity normal
