name: .NET CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Set solution path
      run: |
        BRANCH_NAME=${GITHUB_REF##*/}
        if [ "$BRANCH_NAME" = "task13" ]; then
          echo "SOLUTION_PATH=practica2026/practice2026.slnx" >> $GITHUB_ENV
        elif [ "$BRANCH_NAME" = "task12" ]; then
          echo "SOLUTION_PATH=practica2026/practice2026.slnx" >> $GITHUB_ENV
        elif [ "$BRANCH_NAME" = "task11" ]; then
          echo "SOLUTION_PATH=practica2026/practice2026.slnx" >> $GITHUB_ENV
        else
          echo "SOLUTION_PATH=practice2026.slnx" >> $GITHUB_ENV
        fi

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release

    - name: Run tests
      run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --configuration Release --verbosity normal
